---
title: "Initial analysis report"
date: "`r Sys.Date()`"
author: "Gusinac A"

output:
  html_document:
    toc: true
    toc_float: true
    css: styles.css
---

```{r setup, include=FALSE} 
knitr::opts_chunk$set(warning = FALSE, 
                      message = FALSE, 
                      echo = FALSE, 
                      results = "asis",
                      fig.width = 10,
                      fig.height = 5,
                      fig.alin = "left"
                      ) 
```


```{r}
plot_tabs <- function(plots, method, label_col, label_row) {
  if (method == "matrix") {
    for(i in 1:nrow(plots)) {
      for(j in 1:ncol(plots)) {
        cat(paste0("\n\n### Plot: ", label_col[i], "-", label_row[j], "\n"))
        print(plots[[i,j]])
        cat("\n")
      }
    }
  }
  if (method == "vector") {
    for (i in 1:length(plots)) {
      cat(paste0("\n\n### Plot: ", label_col[i], "\n"))
      print(plots[[i]])
      cat("\n")
    }
  }
}
```

# Automated Analysis


```{r}
if (!is.null(plots$rankstat_plot)) {
  cat("## Rank stats \n")
  plots$rankstat_plot
}
```

```{r}
if (!is.null(plots$alpha_div_plots)) {
  cat("## Alpha diversity {.tabset} \n")
  plot_tabs(plots$alpha_div, 
            method = "vector", 
            label_col = CONTRAST_names)
}

```

```{r}
if (!is.null(plots$pcoa_plots)) {
  cat("## Beta Diversity: Principal Coordinate Analysis (PCoA) {.tabset}")
  plot_tabs(plots$pcoa_plots, 
            method = "matrix", 
            label_col = CONTRAST_names,
            label_row = distance_metrics)
}

```

```{r}
if (!is.null(plots$nmds_plots)) {
  cat("## Beta Diversity: NMDS {.tabset} \n")
  plot_tabs(plots$nmds_plots, 
            method = "matrix",
            label_col = CONTRAST_names,
            label_row = distance_metrics)
}
```

```{r}
if (!is.null(plots$rda_plots)) {
  cat("## Redundancy Analysis (RDA) {.tabset} \n")
  plot_tabs(plots$rda_plots,
            method = "matrix",
            label_col = CONTRAST_names,
            label_row = c("RDA", "PCA"))
}

```

```{r}
if (!is.null(plots$composition_plots)) {
  cat("## Composition {.tabset} \n")
  plot_tabs(plots$composition_plots, 
            method = "matrix", 
            label_col = CONTRAST_names, 
            label_row = feature_contrast)
}

```

```{r}
if (!is.null(plots$Log2FC_plots)) {
  cat("## Log2 FoldChanges {.tabset} \n")
  plot_tabs(plots$Log2FC_plots, 
            method = "matrix", 
            label_col = CONTRAST_names, 
            label_row = feature_contrast)
}

```

<!-- ```{r}
# Function to save content to a temporary file and return the path
save_content <- function(data, extension) {
  temp_file <- tempfile(fileext = extension)
  if (extension == ".mtx") {
    Matrix::writeMM(data, temp_file)
  } else if (extension == ".tsv") {
    data.table::fwrite(data, temp_file, sep = "\t")
  } else if (extension == ".newick") {
    ape::write.tree(data, temp_file)
  }
  return(temp_file)
}

# Data as content to be used for downloadthis
content <- list(counts = omics$countData,
                metadata = omics$metaData, 
                features = omics$featureData)

# Dataframe to be viewed
overview <- data.frame(
  Name = c("counts", "metadata", "features"),
  data_type = c(".mtx", ".tsv", ".tsv")
)

overview[["Download"]] <- vapply(1:nrow(overview), function(i) {
  file_path <- save_content(content[[i]], overview$data_type[i])
  as.character(
    downloadthis::download_file(
      path = file_path,
      output_name = paste0(overview$Name[[i]], overview$data_type[[i]]),
      button_label = "Download",
      button_type = "primary",
      has_icon = TRUE,
      icon = "fa fa-save")
    )
  }, character(1L)
)

# Creates interactive table
DT::datatable(
  overview,
  escape = FALSE,
  options = list(
    columnDefs = list(
      list(targets = ncol(overview), orderable = FALSE),
      list(targets = "_all", className = "dt-center")
    )
  )
)


``` -->

```{r}
cat("### Thanks for using OmicFlow! If you use this package in your research, please cite us.\n\n")
print(utils::citation("OmicFlow"))
```
